name: Build Laravel Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev


      - name: Archive project
        run: zip -r built-project.zip . -x '.git/*' '.github/*' '.env' 'storage/logs/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dentes-built
          path: built-project.zip